:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[[post-api]]
= POST-API

[[카테고리별-게시물-목록-조회]]
== 카테고리별 게시물 목록 조회
operation::post-controller-test/post가_category에_의해_목록_조회된다[snippets='request-parameters,http-response,response-fields']

[[내가-찾는-재능-게시물-목록-조회]]
== 내가 찾는 재능 게시물 목록 조회
operation::post-controller-test/post가_member-talent에_의해_목록_조회된다[snippets='http-request,request-parameters,http-response,response-fields']

[[회원별-게시물-목록-조회]]
== 회원별 게시물 목록 조회
operation::post-controller-test/회원별_post_목록을_조회한다[snippets='path-parameters,http-request,request-parameters,http-response,response-fields']

[[재능-게시글-단건-조회]]
== 재능 게시글 단건 조회
operation::post-controller-test/단일_post를_조회한다[snippets='path-parameters,http-request,http-response,response-fields']

[[재능-게시물-생성]]
== 재능 게시물 생성
operation::post-controller-test/post가_생성된다[snippets='http-request,request-fields,http-response,response-fields']

[[재능-게시물-수정]]
== 재능 게시물 수정
operation::post-controller-test/post를_수정한다[snippets='http-request,request-fields,http-response,response-fields']

[[재능-게시물-삭제]]
== 재능 게시물 삭제
operation::post-controller-test/post가_삭제된다[snippets='path-parameters,http-request,http-response,response-fields']

[[재능-게시물-좋아요-생성]]
== 재능 게시물 좋아요 생성
operation::post-controller-test/post의_like를_중가시킨다[snippets='path-parameters,http-request,http-response,response-fields']

[[재능-게시물-좋아요-취소]]
== 재능 게시물 좋아요 취소
operation::post-controller-test/post의_like를_취소한다[snippets='path-parameters,http-request,http-response,response-fields']
