server:
  port: 8081

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    #      url: jdbc:mysql://데이터베이스 경로/winwin?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    #      username: 데이터베이스 아이디
    #      password: 데이터베이스 비밀번호
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
