server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
      url: ENC(lIjKE4PdYj5818BDfciSgTztEiRtDOt1g+A13kRBpqHnJibN07gl+1sLrI34I5kL9KIXh0vcwwlPdLzXe+DcZsjLr8OhFBV6tP/ePWzJpdbC4fNtcyy777BphqkSpk0csrU0gvPu8y2AyHl+u3xm+Z3jWAAumwzDhTsPXEf2VyMxOw3S5U6c7JvhAcBbqNHCN4W0vqXQX04=)
      username: ENC(kSbVij29Q5IxlMTyH1g0rw==)
      password: ENC(f2DZKexIllOKp9G6wKa2T+E/dqGcnngS)
      driver-class-name: com.mysql.cj.jdbc.Driver

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: ${ENCRYPT_KEY}
