name: dev-deploy

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      # 도커허브 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      # 빌드 이미지 만들어 도커허브로 업로드
      - name: api server build and release to DockerHub
        env:
          NAME: hpwh4457 # DockerHub 계정 명
          IMAGE: winwin # Docker 이미지 이름
          REPO: winwin #  DockerHub 레포 이름
        run: |
          docker build -f ./winwin-be-api/Dockerfile-dev -t $IMAGE ./winwin-be-api
          docker tag $IMAGE:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest
      - name: Github Action to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            /app/deploy2.sh
